[project]
name = "web-scraper-python"
version = "0.1.0"
description = "A Python web crawler project for a boot.dev course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.12.12",
    "beautifulsoup4==4.13.4",
    "requests==2.32.4",
]
